config/routes.rb
Notebooktech::Application.routes.draw do
 

  root :to => 'home#index'
  resources :services
  resources :contacts
  resources :abouts, :only => [:index]
  resources :posts
  resources :locations
  resources :tables
  resources :images, :only => [:index]
  resources :galleries

    #rotas do devise
	scope '/admin' do
        devise_for :users,
                   :controllers => {
             	                     :sessions => "admin/sessions",
             	                     :passwords => "admin/passwords"
        }
    end
  

  #rotas admin
    namespace :admin do
    
      root :to => 'homes#index'
      resources :users
      resources :contacts
      resources :posts
      resources :categories      
      resources :galleries
      resources :types

    end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :posts
  validates_presence_of :name
  default_scope :order => " name ASC"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
attr_accessible :assunto, :body, :email, :fone, :name, :nickname


default_scope :order => "created_at DESC"

validates_presence_of :name , :email, :assunto
validates_format_of :email, :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
captcha :nickname



end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :body, :title, :url,:type_id, :foto


  default_scope :order => "created_at DESC"

  belongs_to :type
  validates_presence_of :title, :type_id
  validates_associated :type


   has_attached_file :foto, :styles => { :small => "710x300#", :medium => "588x180#", :thumb => "110x100#" }
   validates_attachment_presence :foto
   validates_attachment_size :foto, :less_than => 2.megabyte
   validates_attachment_content_type :foto, :content_type => %w(image/png image/jpeg image/gif)

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :bairro, :cep, :cidade, :email, :endereco, :fone

  geocoded_by :endereco
 
  after_validation :geocode

   acts_as_gmappable :process_geocoding => false
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :autor, :body, :subtitle, :title, :url,:category_id

  default_scope :order => "created_at DESC"

  belongs_to :category
  validates_presence_of :title, :category_id
  validates_associated :category
  #verifica se o post esta ativo ou não
 # validates_inclusion_of :ativo, in:[true, false]

  #def self.published
  # where("ativo = ? AND published < ? ", false, Time.current)
 # end


end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name


  has_many :galleries
  validates_presence_of :name
  default_scope :order => " name ASC"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::BaseController
  
  before_filter :controle_extra
  def index
    @galleries = Gallery.paginate page: params[:page], :per_page => 8
    respond_with @galleries
  end

   def show
    @gallery = Gallery.find(params[:id])
    respond_with @gallery
  end

 
  def new
    @gallery = Gallery.new
    respond_with @gallery
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
  end

 
  def create
    @gallery = Gallery.new(params[:gallery])
    flash[:notice] = "Registro salvo com sucesso ! " if @gallery.save
    respond_with @gallery, :location => admin_galleries_path
   
  end
  
  def update
    @gallery = Gallery.find(params[:id])
    flash[:notice] = "Registro salvo com sucesso ! " if @gallery.update_attributes(params[:gallery])
    respond_with @gallery, :location => admin_galleries_path
  end

 
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy
    respond_with @gallery, :location => admin_galleries_path
  end

  def controle_extra
    @types = Type.all
    @galleries = Gallery.paginate page: params[:page], :per_page => 10

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_filter :controle_extra

	def index

	end

	def controle_extra
    @categories = Category.all
    @galleries = Gallery.all
    @postssite = Post.find(:all, :limit => 1, :order=> 'created_at desc')
 @posts = Post.paginate page: params[:page], :per_page => 3
  end
 
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	def textilize(text)
    RedCloth.new(text).to_html.html_safe
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/galleries/_form.html.erb
<article class="module width_3_quarter">
<header>
  <h3 class="tabs_involved">Cadastro de imagens do site</h3>
</header>

<div class="tab_container">
<div id="tab1" class="tab_content">


 <%= form_for [:admin, @gallery] do |f| %>
    <% if @gallery.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@gallery.errors.count, "error") %> : Não foi possível salvar o registro no banco:</h2>
    <% @gallery.errors.full_messages.each do |msg| %>
    <h4 class="alert_error"><%= msg %></h4>
    <% end %>

    </div>
    <% end %>

<fieldset>  
    <label>Selecione a categoria</label>
     <%= f.collection_select(:type_id, @types, :id ,:name, :prompt => true ) %> 

    </fieldset>
      <fieldset>
      <label>Nome</label>
      <%= f.text_field :title %>
      </fieldset>
      <fieldset>
      <label>Endereço do site</label>
      <%= f.text_field :url %>
      </fieldset>
      <fieldset>
       <label>Descrição da imagem</label>
       <%= f.text_area :body, :rows => "3"  %>
      </fieldset>
      <fieldset>
       <%= f.file_field :foto %>
      </fieldset>
    </div>
    <footer>
    <div class="submit_link">
      <%= f.submit 'Salvar registro',:class => 'alt_btn' %>
    <%= link_to admin_galleries_path, :class =>"botaocancelar" do %>
    Cancelar <% end %>
    </div>
    </footer>
  <% end %>  

</div><!-- end of #tab1 -->  

</div><!-- end of .tab_container -->

</article><!-- end of content manager article -->

<!-- render menudireito -->
<%= render  'admin/posts/imagens' %>

<!-- fecha render menudireito -->

<div class="clear"></div> 


</article><!-- end of styles article -->
<div class="spacer"></div>

app/views/admin/galleries/edit.html.erb
<%= render 'form' %>

app/views/admin/galleries/index.html.erb
<article class="module width_full">
<header><h3>Listagem de fotos do site</h3>
<ul class="tabs">
<li>   <%= link_to 'Criar novo registro', new_admin_gallery_path, :title => "criar novo registro" %></li>

</ul></header>
<div class="module_content">
<table>
<tr>

<th width="70%">Foto</th>
<th>Visualizar</th>
<th>Editar</th>
<th>Excluir</th>
<th>Ações</th>


</tr>

<% @galleries.each do |gallery| %>
<tr>   

<td width="70%" align="center"><%= image_tag gallery.foto.url(:thumb) %></td>
<td><%= link_to 'Show', admin_gallery_path(gallery) %></td>
<td><%= link_to 'Edit', edit_admin_gallery_path(gallery) %></td>
<td><%= link_to 'Destroy', admin_gallery_path(gallery), method: :delete, data: { confirm: 'Deletar a imagem ?' } %></td>
</tr>
<% end %>
</table>

<br />
<div><%= will_paginate @galleries %></div>



</div>
<footer>
<div class="submit_link">
<%= link_to admin_root_path, :class =>"botaocancelar" do %>
Inicio <% end %>

</div>
</footer>
</article><!-- end of post new article -->

app/views/admin/galleries/new.html.erb
<%= render 'form' %>

app/views/admin/galleries/show.html.erb
<article class="module width_3_quarter">
<header>
  <h3 class="tabs_involved">Listagem de fotos</h3>
</header>

<div class="tab_container">
<div id="tab1" class="tab_content">
	<label>Titulo:<%= @gallery.title %></label><br>
	<label>Url: <%= @gallery.url %></label><br>
	<label><%= @gallery.body %></label><br>

<%= image_tag @gallery.foto.url(:thumb) %>
<%= image_tag @gallery.foto.url(:medium) %>
<%= image_tag @gallery.foto.url(:small) %>
<br>
<%= link_to admin_galleries_path, :class =>"botaocancelar" do %>
    Voltar <% end %>
 

<br>

</div><!-- end of #tab1 -->  

</div><!-- end of .tab_container -->

</article><!-- end of content manager article -->

<!-- render menudireito -->
<%= render  'admin/homes/menudireito' %>

<!-- fecha render menudireito -->

<div class="clear"></div> 


</article><!-- end of styles article -->
<div class="spacer"></div>