config/routes.rb
Notebooktech::Application.routes.draw do
 

  root :to => 'home#index'
  resources :services
  resources :contacts
  resources :abouts, :only => [:index]
  resources :posts
  resources :locations
  resources :tables
  resources :images, :only => [:index]
  resources :galleries

    #rotas do devise
	scope '/admin' do
        devise_for :users,
                   :controllers => {
             	                     :sessions => "admin/sessions",
             	                     :passwords => "admin/passwords"
        }
    end
  

  #rotas admin
    namespace :admin do
    
      root :to => 'homes#index'
      resources :users
      resources :contacts
      resources :posts
      resources :categories      
      resources :galleries
      resources :types

    end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :posts
  validates_presence_of :name
  default_scope :order => " name ASC"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
attr_accessible :assunto, :body, :email, :fone, :name, :nickname


default_scope :order => "created_at DESC"

validates_presence_of :name , :email, :assunto
validates_format_of :email, :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
captcha :nickname



end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :body, :title, :url,:type_id, :foto


  default_scope :order => "created_at DESC"

  belongs_to :type
  validates_presence_of :title, :type_id
  validates_associated :type


   has_attached_file :foto, :styles => { :small => "710x300#", :medium => "588x180#", :thumb => "110x100#" }
   validates_attachment_presence :foto
   validates_attachment_size :foto, :less_than => 2.megabyte
   validates_attachment_content_type :foto, :content_type => %w(image/png image/jpeg image/gif)

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :bairro, :cep, :cidade, :email, :endereco, :fone

  geocoded_by :endereco
 
  after_validation :geocode

   acts_as_gmappable :process_geocoding => false
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :autor, :body, :subtitle, :title, :url,:category_id

  default_scope :order => "created_at DESC"

  belongs_to :category
  validates_presence_of :title, :category_id
  validates_associated :category
  #verifica se o post esta ativo ou não
 # validates_inclusion_of :ativo, in:[true, false]

  #def self.published
  # where("ativo = ? AND published < ? ", false, Time.current)
 # end


end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name


  has_many :galleries
  validates_presence_of :name
  default_scope :order => " name ASC"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < Admin::BaseController

	def index
   @contacts = Contact.paginate page:params[:page], :per_page => 6
	end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_filter :controle_extra

	def index

	end

	def controle_extra
    @categories = Category.all
    @galleries = Gallery.all
    @postssite = Post.find(:all, :limit => 1, :order=> 'created_at desc')
 @posts = Post.paginate page: params[:page], :per_page => 3
  end
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :controle_extra
  
  def index
   @posts = Post.paginate page: params[:page], :per_page => 3
    respond_with @post
   
  end

 
  def show
    @post = Post.find(params[:id])
    respond_with @post
  end



  def controle_extra
    @categories = Category.all
    @galleries = Gallery.all
    @postssite = Post.find(:all, :limit => 1, :order=> 'created_at desc')
    @posts = Post.paginate page: params[:page], :per_page => 3
  end


end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	def textilize(text)
    RedCloth.new(text).to_html.html_safe
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/homes/_menu.html.erb
<form class="quick_search">
			<input type="text" value="Quick Search" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
		</form>
		<hr/>
		<% if user_signed_in? %>
		<h3>Cadastros</h3>
		<ul class="toggle">
			<li class="icn_new_article"><%= link_to new_admin_post_path do %>
				Novo Artigo <% end %></li>
			
			<li class="icn_categories"><%= link_to new_admin_category_path do %>
				Categorias
				 <% end %></li>
				 <li class="icn_categories"><%= link_to new_admin_type_path do %>
				Categorias de imagens
				 <% end %></li>
				 	<li class="icn_photo"><%= link_to new_admin_gallery_path do %>
				 		Cadastro de fotos <% end%></li>
			<li class="icn_profile"><%= link_to new_admin_user_path do %>
				 		Cadastro de usuários <% end%></li>
		</ul>
		<h3>Relatórios</h3>
		<ul class="toggle">
			<li class="icn_categories"><%= link_to admin_posts_path do %>
				Listagem de artigos<% end %></li>
			<li class="icn_categories"><%= link_to admin_categories_path do %>
				Listagem de categorias<% end %></li>
				<li class="icn_categories"><%= link_to admin_types_path do %>
				Listagem categorias de imagens<% end %></li>
			<li class="icn_profile"><%= link_to admin_contacts_path do %>
				E-mail do site<% end %></li>
				<li class="icn_add_user"><%= link_to admin_users_path do %>
				Listagem de usuários<% end %></li>
				<li class="icn_photo"><%= link_to admin_galleries_path do %>
					Listagem de fotos<% end %></li>
		</ul>
		<h3>Media</h3>
		<ul class="toggle">
			<li class="icn_folder"><a href="#">File Manager</a></li>
			<li class="icn_photo"><a href="#">Gallery</a></li>
			<li class="icn_audio"><a href="#">Audio</a></li>
			<li class="icn_video"><a href="#">Video</a></li>
		</ul>
		<h3>Admin</h3>
		<ul class="toggle">
			<li class="icn_settings"><a href="#">Options</a></li>
			<li class="icn_security"><a href="#">Security</a></li>
			<li class="icn_jump_back">

			 <%= link_to  destroy_user_session_path, :method => :delete, :title => "Sair do sistema"  do %>
			 Sair 
			 <% end %>

			</li>
		</ul>
		
		<footer>
			<hr />
			<p><strong>Copyright &copy; 2013 Notebooktech</strong></p>
			<p>Theme by <a href="http://erloncarlos.com" target="_blank">WebMaster</a></p>
		</footer>

		<% end %>

app/views/admin/homes/_menudireito.html.erb
<article class="module width_quarter">
<header><h3>Messages</h3></header>
			<div class="message_list">
				<div class="module_content">
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					<div class="message"><p>Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor.</p>
					<p><strong>John Doe</strong></p></div>
					
				</div>
			</div>
			<footer>
				<form class="post_message">
					<input type="text" value="Message" onfocus="if(!this._haschanged){this.value=''};this._haschanged=true;">
					<input type="submit" class="btn_post_message" value=""/>
				</form>
			</footer>
			</article><!-- end of messages article -->

app/views/admin/homes/index.html.erb
		
		<h4 class="alert_info">Welcome to the free MediaLoot admin panel template, this could be an informative message.</h4>
		
		
		
		<article class="module width_3_quarter">
		<header><h3 class="tabs_involved">Content Manager</h3>
		<ul class="tabs">
   			<li><a href="#tab1">Posts</a></li>
    		<li><a href="#tab2">Comments</a></li>
		</ul>
		</header>

		<div class="tab_container">
			<div id="tab1" class="tab_content">


			<table class="tablesorter" cellspacing="0"> 
			<thead> 
				<tr> 
   					<th>Data</th>
    				<th>Nome</th> 
    				<th>E-mail</th> 
    				<th>assunto</th> 
    				<th>Ações</th> 
				</tr> 
			</thead> 
			<tbody> 
				
			 <% @contacts.each do |c| %>
                <tr> 
                  <td><%= c.created_at.strftime("%d de %b - %y") %></td>
                    <td><%= c.name %></td> 
                    <td><%= c.email %></td> 
                    <td><%= c.assunto %></td> 
                    <td>
                    	 <%= link_to admin_contact_path(c) do %>
                        <%= image_tag "admin/icn_search.png", :title=> "Visualizar" %><% end %>
                    	</td> 
                </tr> 
               <% end %>
                 <tr><td colspan="5"><%= will_paginate @contacts %></td></tr>
			</tbody> 
			</table>
			</div><!-- end of #tab1 -->
			
			
			
		</div><!-- end of .tab_container -->
		
		</article><!-- end of content manager article -->
		<!-- render menudireito -->		
			<%= render  'admin/homes/menudireito' %>		
		<!-- fecha render menudireito -->
		
		<div class="clear"></div>
		
		<article class="module width_full">
			<header><h3>Post New Article</h3></header>
				<div class="module_content">
						<fieldset>
							<label>Post Title</label>
							<input type="text">
						</fieldset>
						<fieldset>
							<label>Content</label>
							<textarea rows="12"></textarea>
						</fieldset>
						<fieldset style="width:48%; float:left; margin-right: 3%;"> <!-- to make two field float next to one another, adjust values accordingly -->
							<label>Category</label>
							<select style="width:92%;">
								<option>Articles</option>
								<option>Tutorials</option>
								<option>Freebies</option>
							</select>
						</fieldset>
						<fieldset style="width:48%; float:left;"> <!-- to make two field float next to one another, adjust values accordingly -->
							<label>Tags</label>
							<input type="text" style="width:92%;">
						</fieldset><div class="clear"></div>
				</div>
			<footer>
				<div class="submit_link">
					<select>
						<option>Draft</option>
						<option>Published</option>
					</select>
					<input type="submit" value="Publish" class="alt_btn">
					<input type="submit" value="Reset">
				</div>
			</footer>
		</article><!-- end of post new article -->
		
		<h4 class="alert_warning">A Warning Alert</h4>
		
		<h4 class="alert_error">An Error Message</h4>
		
		<h4 class="alert_success">A Success Message</h4>
		
		
		</article><!-- end of styles article -->
		<div class="spacer"></div>

app/views/home/index.html.erb
  <div class="12u">
    <div class="5grid-layout">
      <div class="row">
        <div class="4u">
          <section>
            <p><a href="#"> <%= image_tag 'administrador.jpg' %></a></p>
            <p>O melhor sistema para controle físico e financeiro para sua empresa.<br>
Atende comércio em geral.<br>
Modulos especificos para: Indústrias, Prestadores de Serviços,  Supermercados<br>
Indústrias: Pequenas indústrias de fabricação em série. Controle de produção e de estoque, com cálculo de mão de obra direta e indireta embutido no custo do produto final, feito diretamente no sistema.<br>

Comércio em geral: Atende a empresas de pequeno porte em todos os ramos de comércio varejista que necessitem de sistema de automação comercial que possua robustez e controles integrados. 
</p>
             <p><%= link_to services_path ,:title => "Leia mais..." do %>
          Leia mais...
             <% end %>
        </p>
          </section>
        </div>
       
        <div class="4u">
          <section>
            <p><a href="#"><%= image_tag 'comercial.jpg' %></a></p>
            <p>Modernidade e eficiência em automação comercial.<br>

Permite a emissão de cupom fiscal e processar todas as funções pertinentes a essa função, adequadas ao que orienta a legislação ER-PAF-ECF.<br>

Pode ser utilizado sozinho ou como PDV dos retaguardas Sistema Administrador G4 ou Sistema Gerencial G4.<br>
Indicado para pequenas e micro empresas de comércio em geral.<br>

Lojas de informática, comércio de tintas, cosmésticos e perfumarias, confecções, calçados, papelaria, bicicletarias, auto elétricas, lojas de cd, livrarias, joalherias, lojas de conveniência, lojas de móveis, mercadinhos, etc.<br>


            <p><%= link_to services_path ,:title => "Leia mais..." do %>
          Leia mais...
             <% end %>
        </p>
          </section>
        </div>
         <div class="4u">
          <section>
            <p><a href="#"><%= image_tag 'gerencial.jpg' %></a></p>
            <p>O gerente que sua empresa estava esperando.<br>

Atende comércio em geral e modulos especificos, sem custo adicional!

    Restaurantes, Restaurantes com dispositivos móveis (MG4), 
    Prestadores de Serviços, 
    Oficinas (com Ordem de Serviços), 
    Farmácias<br>
Comércio em geral: Lojas de informática, materiais de construção, comércio de tintas, cosmésticos e perfumarias, drogarias, confecções, papelarias, bicicletarias, auto elétricas, lojas de disco, lojas de calçados, livrarias, joalherias, lojas de 1,99, lojas de conveniência, lojas de móveis, óticas, distribuidoras, ferragens, restaurantes, mercados, postos de combustível, prestadoras de serviço em geral, etc.</p>
           <p><%= link_to services_path ,:title => "Leia mais..." do %>
          Leia mais...
             <% end %>
        </p>
          </section>
        </div>


      </div>
    </div>
  </div>

<!--clouna nova -->
<div class="12u">
    <div class="5grid-layout">
      <div class="row">
        <div class="4u">
          <section>
            <p><a href="#"> <%= image_tag 'banner_notebook.png' %></a></p>
            <p>Consertamos notebooks, utilizando peças de qualidade e marcas de renome. Além de fazer com que o notebook volte a funcionar pela substituição de alguma peça defeituosa, também realizamos a configuração correta do hardwarer e do Sistema Operacional, para melhorar o desempenho de seu equipamento.
</p>
             <p><%= link_to services_path ,:title => "Leia mais..." do %>
          Leia mais...
             <% end %>
        </p>
          </section>
        </div>
       
        <div class="4u">
          <section>
            <p><a href="#"><%= image_tag 'banner_hds.png' %></a></p>
            <p>Recuperação de hds todas as marcas estamos capacitados tecnologicamente para recuperar dados de todas as marcas e modelos de HD estragado. Recuperar Hard Disks com vários sintomas também é um serviço oferecido pelo nosso laboratório de recuperação de dados em HD:</p>
             <p><%= link_to services_path ,:title => "Leia mais..." do %>
          Leia mais...
             <% end %>
        </p>
          </section>
        </div>
         <div class="4u">
          <section>
            <p><a href="#"><%= image_tag 'banner_programas.png' %></a></p>
            <p>Instalamos programas, aplicativos comerciais, aplicativos mobile e jogos em seu computador, notebook ou dispositivos moveis. Configuramos o seu software para que funcione perfeitamente, fazendo com que o programa em questão seja executado de maneira rápida e estável.</p>
           <p><%= link_to services_path ,:title => "Leia mais..." do %>
          Leia mais...
             <% end %>
        </p>
          </section>
        </div>

<!--outro linha abaixo-->
 


      </div>
    </div>
  </div>