config/routes.rb
Notebooktech::Application.routes.draw do
 

  root :to => 'home#index'
  resources :services
  resources :contacts
  resources :abouts, :only => [:index]
  resources :posts
  resources :locations
  resources :tables
  resources :images, :only => [:index]
  resources :galleries

    #rotas do devise
	scope '/admin' do
        devise_for :users,
                   :controllers => {
             	                     :sessions => "admin/sessions",
             	                     :passwords => "admin/passwords"
        }
    end
  

  #rotas admin
    namespace :admin do
    
      root :to => 'homes#index'
      resources :users
      resources :contacts
      resources :posts
      resources :categories      
      resources :galleries
      resources :types

    end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :posts
  validates_presence_of :name
  default_scope :order => " name ASC"
end

app/models/contact.rb
class Contact < ActiveRecord::Base
attr_accessible :assunto, :body, :email, :fone, :name, :nickname


default_scope :order => "created_at DESC"

validates_presence_of :name , :email, :assunto
validates_format_of :email, :with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
captcha :nickname



end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :body, :title, :url,:type_id, :foto


  default_scope :order => "created_at DESC"

  belongs_to :type
  validates_presence_of :title, :type_id
  validates_associated :type


   has_attached_file :foto, :styles => { :small => "710x300#", :medium => "588x180#", :thumb => "110x100#" }
   validates_attachment_presence :foto
   validates_attachment_size :foto, :less_than => 2.megabyte
   validates_attachment_content_type :foto, :content_type => %w(image/png image/jpeg image/gif)

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :bairro, :cep, :cidade, :email, :endereco, :fone

  geocoded_by :endereco
 
  after_validation :geocode

   acts_as_gmappable :process_geocoding => false
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :autor, :body, :subtitle, :title, :url,:category_id

  default_scope :order => "created_at DESC"

  belongs_to :category
  validates_presence_of :title, :category_id
  validates_associated :category
  #verifica se o post esta ativo ou não
 # validates_inclusion_of :ativo, in:[true, false]

  #def self.published
  # where("ativo = ? AND published < ? ", false, Time.current)
 # end


end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :name


  has_many :galleries
  validates_presence_of :name
  default_scope :order => " name ASC"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
 
 before_filter :controle_extra
  def index
    @users = User.paginate page: params[:page], :per_page => 10
    respond_with @users
  end

  def new
    @user = User.new
    respond_with @user
  end
  
  def edit
    @user = User.find(params[:id])
  end
 
  def create
    @user = User.new(params[:user])
    flash[:notice] = "Registro salvo com sucesso !" if @user.save
    respond_with @user, :location => admin_users_path    
    
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    flash[:notice] = "Registro salvo com sucesso !" if @user.update_attributes(prams[:user])
    respond_with @user, :location => admin_users_path   
  end

 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_with @user, :location => admin_users_path    

  
  end


  def controle_extra

  @categories = Category.all
  @galleries = Gallery.paginate page: params[:page], :per_page => 10
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_filter :controle_extra

	def index

	end

	def controle_extra
    @categories = Category.all
    @galleries = Gallery.all
    @postssite = Post.find(:all, :limit => 1, :order=> 'created_at desc')
 @posts = Post.paginate page: params[:page], :per_page => 3
  end
 
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


	def textilize(text)
    RedCloth.new(text).to_html.html_safe
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<article class="module width_3_quarter">
<header>
  <h3 class="tabs_involved">Cadastro de usuários</h3>
</header>

<div class="tab_container">
<div id="tab1" class="tab_content">

<%= form_for [:admin , @user] do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
<h4  class="alert_warning"><%= pluralize(@user.errors.count, "error") %> Não foi possível salvar o registro : </h4>

<ul>
<% @user.errors.full_messages.each do |msg| %>
<li>
<h4 class="alert_error"><%= msg %></h4></li>
<% end %>
</ul>
</div>
<% end %>


<fieldset>
<label>Nome</label>
<%= f.text_field :name %>
</fieldset>
<fieldset>
<label>E-mail</label>
<%= f.text_field :email %>

</fieldset>
<fieldset>
<label>Senha</label>
<%= f.password_field :password %>
</fieldset>
<fieldset>
<label>Senha Confirmar</label>
<%= f.password_field :password_confirmation %>
</fieldset>


<div class="submit_link">
<%= f.submit "Salvar registro", :class =>"alt_btn" %>
<%= link_to admin_users_path, :class =>"botaocancelar" do %>
    Cancelar
<% end %> 
</div>
<% end %>

</div><!-- end of #tab1 -->  

</div><!-- end of .tab_container -->

</article><!-- end of content manager article -->

<!-- render menudireito -->


<!-- fecha render menudireito -->

<div class="clear"></div> 

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb
<article class="module width_3_quarter">
<header><h3 class="tabs_involved">Listagem de usuários</h3>
<ul class="tabs">
<li><%= link_to new_admin_user_path do %>
Novo registro <% end %></li>

</ul>
</header>

<div class="tab_container">
<div id="tab1" class="tab_content">


<table class="tablesorter" cellspacing="0"> 
<thead> 
<tr> 
  
<th>Nome</th>
<th>E-mail</th> 


<th>Ações</th> 
</tr> 
</thead> 
<tbody> 

<% @users.each do |c| %>
<tr> 
  <td><%= c.name %></td> 
<td><%= c.email %></td>



<td>
<%= link_to edit_admin_user_path(c) do %>
<%= image_tag "admin/icn_edit.png", :title=> "Visualizar" %> <% end %>
<%= link_to admin_user_path(c), confirm: 'Deletar arquivo, Tem certeza ?', method: :delete , :title => "Excluir arquivo"  do %>
<%= image_tag "admin/icn_trash.png" %> <% end %>



</td> 
</tr> 
<% end %>
<tr><td colspan="5"><%= will_paginate @users %></td></tr>
</tbody> 
</table>
</div><!-- end of #tab1 -->



</div><!-- end of .tab_container -->

</article><!-- end of content manager article -->

<%= render  'admin/homes/menudireito' %>    

app/views/admin/users/new.html.erb
<%= render 'form' %>